### ISSUE TITLE
A question about the " f.write() " function !

### ISSUE THREAD

**Issue by ghost** [rahul-ramadas/LeetcodeDownloader#3]
Thank you so much, your script is very helpful. But When I first ran it, A error called " gbk can not decode charactor ..... in position ... "  was raised, then I modify

line 173 

with open(os.path.join(prob_dir, filename)) as f:

to 

with open(os.path.join(prob_dir, filename), "w", encoding='utf-8') as f:

then it worked well.
Maybe that was a bug? I am not sure.

**Comment by rahul-ramadas** [comment]
It's probably because some of your solutions seem to have some special characters in them that are outside the ANSI range. I will take your suggestion and explicitly set the encoding to UTF-8. Thanks!
